### ISSUE TITLE
Sociogram Interface (59)

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#126]
## General overview:

This interface has three purposes: (1) positioning the nodes amongst the concentric circles, (2) linking the nodes together (creating edges), and (3) selecting nodes that have a given attribute. Each instance of this interface can have one or more tasks, which are switched between using the _prompt swiper_. 

The definition of each prompt also contains the name of the variables where the result of the interaction should be stored. For example, a layout task would include the node variable to store the coordinates on. An edge creation task would define the edge type, and any other attributes that the edge should have. A node nomination task would define the node variable and its value. 

Also important is that the prompt should contain a definition of which visual variables should be shown on the layout. For example, on a given prompt, the definition should define: which nodes are highlighted, which edges are shown (could be edges of multiple types, and therefore different colors), and which layout variable is used for the node coordinates. 

# Tasks

## Research (10)

- [x] Research UI technology for interface (e.g. Canvas for edges, vectors for nodes...) (4)
- [x] Create sociogram interface (2)
- [x] Build prompt swiper/slider. Perhaps re-use the component from name generator. (4)

### Container and background component (5)

- [x] Create container (1) 
- [x] Create background component (1)
- [x] Background: Any number of rings between 0 and 7. Should also have a mode that biases size towards inner rings (skew mode) - default. I used layered opacity to achieve the variable color effect.
- [x] BONUS: Meeting today suggested that people also want to be able to provide an arbitrary image as the background for this screen. (4)

### Add node from top left (20)

- [x] Create node bucket component: Show 1 node at a time (until it's positioned), configure order they are shown (say by node attribute), once node is dropped next node appears (8)
- [x] Create Node layout component (1)
- [x] Position nodes in Node layout component (4)
- [x] When dropped, save x/y position against specified node attributes for coordinate (defined on the current prompt) (8) 

### Link nodes (20)

- [x] Create link component (1)
- [x] Build link component (canvas view showing edges). (16)
- [x] Click one node and then another to add an edge between them to the network (4)

### Select a node (4)
- [x] When a node is clicked, add the related attribute from the prompt to the node (4)

**Comment by jthrilly** [comment]
Meeting with Bernie suggested that we explore alternative UI for node placement to explore biases associated with a fixed placement ("stack") of nodes in one position (i.e top right for RADAR. middle left for DPhil).

The proposal is to explore an autohiding panel, likely placed at the bottom, that acts as a container for both the layout task/instructions and the nodes themselves. When a node is being dragged, the container shrinks/minimizes to show only the task.

**Comment by jthrilly** [comment]
* Feedback from Michelle in #127 suggests the need to support linking entities from a roster "from the perspective of ego". For example, relationships perceived between students in a classroom.
* This might also imply/emphasize the need for automatic layout in certain cases. In the above example. perhaps a realtime force directed layout, with isolate binning.

**Comment by wwqrd** [comment]
## Estimate {59}

[ ] Research UI technology for interface (e.g. Canvas for edges, vectors for nodes...) {8}
[ ] Create sociogram interface component {0.5}
[ ] Build prompt swiper/slider. Perhaps re-use the component from name generator {2}
Concentric circles container {48.5}

[ ] Create concentric circles container {0.5}
[ ] Create background component: Any number of rings between 0 and 7. Should also have a mode that biases size towards inner rings (skew mode) - default. I used layered opacity to achieve the variable color effect. {4}
Add node from top left {20}

[ ] Create node bucket component: Show 1 node at a time (until it’s positioned), configure order they are shown (say by node attribute), once node is dropped next node appears {8}
[ ] When dropped, save x/y position against specified node attributes for coordinate (defined on the current prompt) {4}
[ ] Create Node layout component, which displays nodes in position {8}
Link nodes {20}

[ ] Click one node and then another to add an edge between them to the network {4}
[ ] Create link component (canvas view showing edges) {16}
Select a node {4}

[ ] When a node is clicked, add the related attribute from the prompt to the node {4}

**Comment by jthrilly** [comment]
# Total Estimate  (33.5)

## Research (8)
- Research UI technology for interface (e.g. Canvas for edges, vectors for nodes...) (4)
- Create sociogram interface component (2)
- Build prompt swiper/slider. Perhaps re-use the component from name generator (2)

## Concentric circles container (25.5)
### Container and background component (4.5)
- Create concentric circles container (0.5)
- Create background component: Any number of rings between 0 and 7. Should also have a mode that biases size towards inner rings (skew mode) - default. I used layered opacity to achieve the variable color effect. (4)

### Add node from top left (10)

- Create node bucket component: Show 1 node at a time (until it’s positioned), configure order they are shown (say by node attribute), once node is dropped next node appears (4)
- When dropped, save x/y position against specified node attributes for coordinate (defined on the current prompt) (2)
- Create Node layout component, which displays nodes in position (4)

### Link nodes (10)

- Click one node and then another to add an edge between them to the network (2)
- Create link component (canvas view showing edges) (8)

### Select a node (1)
- When a node is clicked, add the related attribute from the prompt to the node (1)

**Comment by rebeccamadsen** [comment]
Total Estimate (54)
--

### Research (13)

- Research UI technology for interface (e.g. Canvas for edges, vectors for nodes...) (8)
- Create sociogram interface component (2)
- Build prompt swiper/slider. Perhaps re-use the component from name generator (4)

### Concentric circles container (41)
**Container and background component (5)**

- Create concentric circles container (1)
- Create background component: Any number of rings between 0 and 7. Should also have a mode that biases size towards inner rings (skew mode) - default. I used layered opacity to achieve the variable color effect. (4)

**Add node from top left (20)**

- Create node bucket component: Show 1 node at a time (until it’s positioned), configure order they are shown (say by node attribute), once node is dropped next node appears (8)
- When dropped, save x/y position against specified node attributes for coordinate (defined on the current prompt) (4)
- Create Node layout component, which displays nodes in position (8)

**Link nodes (12)**

- Click one node and then another to add an edge between them to the network (4)
- Create link component (canvas view showing edges) (8)

**Select a node (4)**

- When a node is clicked, add the related attribute from the prompt to the node (4)

**Comment by katebanner** [comment]
Animation to improve discoverability on sociogram screens 

From demo feedback meeting with Cui Yang on 7/28/2017:
Cui suggested that we add animations (e.g. glowing/bouncing/etc.) to the sociogram screen so that participants know that nodes should be pulled down from the top. Animations would "highlight" walk through of the app.

We may also want to consider adding animations to other screens on the app (and maybe the architect as well) that will improve flow and minimize the need for explanation or direction from the researcher during the interview.

**Comment by katebanner** [comment]
Animations to improve discoverability on sociogram screen

https://github.com/codaco/Network-Canvas/issues/199

**Comment by katebanner** [comment]
Feedback @berniehogan collected at SMS July 2017: 
Lots of requests (especially from Betina’s people) to have custom maps in the back of the sociogram screen.

**Comment by wwqrd** [comment]
> Meeting today suggested that people also want to be able to provide an arbitrary image as the background for this screen.

This is very interesting, it already makes multi-file protocols a prerequisite, unless we use data-uris.

**Comment by wwqrd** [comment]
@jthrilly I'd like some direction on:

> When dropped, save x/y position against specified node attributes for coordinate (defined on the current prompt)

When we discussed this before, this became the desired outcome because it'll support multiple layouts.

Given that prompt attributes are defined like:

```js
"prompts": [
  {
    id: '6cl2',
    title: 'Within the past 6 months, who have you felt close to?',
    nodeAttributes: {
      special_category: 46,
      close_friend: true,
    },
  },
  // ...
],
```

I'm unsure how to assign the data to the node.

If we use the prompt functionality we've used in the Name Generator interface, it'll probably need to be a special case.

Perhaps a layout keyword would work best?:

```js
"prompts": [
  {
    id: '6cl2',
    title: 'What friendship groups are in your network?',
    nodeAttributes: {
      layout: 'friendships',  // reserved attribute
    },
  },
  // or
  {
    id: '6cl2',
    title: 'What friendship groups are in your network?',
    layout: 'friendships',  // new property on prompts
  },
],


```

**Comment by jthrilly** [comment]
@wwqrd - just checking that we covered your questions above in our chat yesterday. Let me know if not.

(Sorry for not seeing this!)

**Comment by wwqrd** [comment]
I went for the second approach in the prompts config, and based on our conversation it's stored directly on the node:

```
// config
"prompts": [
  {
    id: '6cl2',
    title: 'What friendship groups are in your network?',
    layout: 'friendshipsLayout',
    ...
  },
  ...
],
```

and:

```
// node
{
  uid: '6cl2',
  friendshipsLayout: {
    x: 100,
    y: 100,
  },
  ...
}
```

**Comment by jthrilly** [comment]
Perfect.

**Comment by katebanner** [comment]
https://github.com/codaco/Network-Canvas/issues/218 #218
