### ISSUE TITLE
Add missing styles for name generator (12.5)

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#169]
Add styles from the style guide.

# Tasks

- [x] node "inactive" style (0.5)
- [x] node selected style should have a "glow" (4)
- [x] type size should adjust if name exceeds width. Forced hyphenation should be used as a last resort. This will need to happen programmatically. Note: max name length = 8 chars. No min name length (could be a single char or even an emoji). (4)
- [x] name generator panel background specified as opacity rather than panel color (check style guide to confirm this) (1)
- [x] name generator panel node opacity (1)
- [x] add color variants for nodes (2)

**Comment by jthrilly** [comment]
@jamieshark is this stale? are these implemented?

**Comment by jthrilly** [comment]
- panel where nodes from a different course have a difference color

**Comment by jamieshark** [comment]
## Estimate (8-9)
- node "inactive" style **(already implemented)**
- node selected style should have a "glow" (2-3)
- type size should adjust if name exceeds width (no word wrap?) (2)
- name generator panel background opacity (1)
- name generator panel type opacity (is this also node opacity?) (1)
- add color variants for nodes (2)

**Comment by wwqrd** [comment]
## Estimate (5)

- node "inactive" style (0.5)
- node selected style should have a "glow" (1)
- type size should adjust if name exceeds width (no word wrap?) (2)
- name generator panel background opacity (0.5)
- name generator panel type opacity (is this also node opacity?) (?)
- add color variants for nodes (1)

**Comment by jthrilly** [comment]
## Estimate (7)

- node "inactive" style (0.5)
- node selected style should have a "glow" (1)
- type size should adjust if name exceeds width (4)
- name generator panel background opacity (0.5)
- name generator panel type opacity  (?)
- add color variants for nodes (1)

**Comment by rebeccamadsen** [comment]
Estimate (8)
--

- node "inactive" style (.5)
- node selected style should have a "glow" (2)
- type size should adjust if name exceeds width (2)
- name generator panel background opacity (.5)
- name generator panel node opacity (1)
- add color variants for nodes (2)
