### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#175]
Right now, everything is static. Animation is _vital_ to our user experience. Elsewhere (https://github.com/codaco/Network-Canvas-UI/blob/merging-styles-branch/styles/global/core/_animation.scss) we specify the building blocks of our animation system. The following will need to be implemented both in our in-app CSS, and our base styles repo (for example, component state animation [button highlighting, etc.] is probably universal enough to go into the UI repo, whereas 'between stage transitions' will be implemented in-app using the `_animation.scss` parameters).

The following is a general list of items that need animation.

- Screens should transition as the interview advances forwards or backwards. I am open to suggestions about how this should look, but the existing approach was to fade to black with a loader, and then fade back in.
- Node state changes should animate. For example, selecting/deselecting, and changes in size when dragging should transition nicely.

### Sub-tasks
- [x] Fix node color (use new palette())
- [x] Make stage fade to rich-black
- [x] Modal animation
- [x] Node state animations (selected toggle)
- [x] Animate away empty panels, if possible?
- [x] Stagger node animate in, if possible?
- [ ] Fix animations for menu

**Comment by jthrilly** [comment]
Okay, we are looking good. Here are some things to add:

- Modal show/hide animation. Mimmick the existing animation if you can (slide in from above/below - either is fine - along with opacity fade, background blur and fade - may not be performant, will need to test)
- In the prototype, the node show animations were staggered within each container. So for example, they animated in sequentially in both the main node list, and the side panels. Can we do this again?
- You're going to hate this. In the prototype, the panels were 'aware' of their content, meaning that they would animate away if they became empty. Can we do this? It is somewhat complicated by the fact that we have two scenarios. (1) - easy - there is one panel visible, and it has no nodes and so it animates away. The main node list then becomes full width. (2) - complex - there are two panels, where one becomes empty and animates away, the second should become full height. I think something like a scale to invisible while fading out opacity would be appropriate for removing a panel, while hopefully flex box lets us animate the transition to full height/full width for any remaining panels.

**Comment by jthrilly** [comment]
Small things:

- Default node color seems to be missing. Probably related to the changes with the UI repo, but it would be good to get it back.
- The between stage animation should fade to black rather than the purple.

**Comment by wwqrd** [comment]
RE fixing the menu animation: Suggest we make that an issue on the UI repo, I think that's where these styles are now defined?

**Comment by jthrilly** [comment]
> RE fixing the menu animation: Suggest we make that an issue on the UI repo, I think that's where these styles are now defined?

Agreed, and besides I may have fixed this myself in Rebecca's branch. Let's leave for now, and comment in  if further changes are needed.

**Comment by jthrilly** [comment]
Maybe close this issue with your PR when you merge.
