### ISSUE TITLE
Initial data export functionality (9)

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#179]
As discussed in #170, we need a basic data export function. This will live in the settings menu. More details to follow.

**Comment by jthrilly** [comment]
# Overview

In the Server app, we will be implementing CSV exporting first since this is the format that has been most requested. 

However, due to the difficulty of supporting node and edge attributes in this format (necessitating multiple files and a ZIP file to bundle), we will implement the GraphML export functionality from the legacy version for the alpha release. GraphML can be converted to CSV, and will support node and edge attributes in a single file.

- [Information about the graphML format](http://graphml.graphdrawing.org)

# Tasks

- [ ] Create session menu download link
- [ ] Backport and integrate GraphML generation code from here: https://github.com/jthrilly/NetworkCanvas/blob/sunbelt/js/session.js#L16-L150
- [ ] Implement file download triggering in electron contexts
- [ ] Implement file download triggering in Cordova contexts

**Comment by wwqrd** [comment]
## Estimate (5.5)

- Create session menu download link (0.5)
- Backport and integrate GraphML generation code (1)
- Implement file download triggering in electron contexts (2)
- Implement file download triggering in Cordova contexts (2)

**Comment by rebeccamadsen** [comment]
Estimate (7)
--

- Create session menu download link (1)
- Backport and integrate GraphML generation code (2)
- Implement file download triggering in electron contexts (2)
- Implement file download triggering in Cordova contexts (2)

**Comment by jthrilly** [comment]
## Estimate: 8.5

- Create session menu download link (0.5) 
- Backport and integrate GraphML generation code (4)
- Implement file download triggering in electron contexts (2)
- Implement file download triggering in Cordova contexts (2)
