### ISSUE TITLE
Implement mobile UI (12)

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#191]
In general, responsive UI is not present. It is needed for proper tablet usability. The following need to be implemented.

# Tasks

- [x] Simple media query style mixin that lets us differentiate between desktop and tablet contexts. (2)
- [x] Mobile UI for the menu system. (4)
- [x] Mobile adaptations to typography, node, and image asset (e.g. button) sizing (8)

**Comment by wwqrd** [comment]
My preference for implementation of responsive styles is per component rather than globally. It keeps styles from spilling out where they aren't needed, and keeps components theoretically portable.

```sass
# in my-component.sass

.my-component {
  ...general styles here, mobile first?
}

+tablet { // mixin for @media
  .my-component {
    // tablet specific overrides
  }
}

+desktop {
  .my-component {
    // desktop specific overrides
  }
}
```

Does anyone else have thoughts on this?

**Comment by jthrilly** [comment]
I agree with you about doing this on a component basis.

**Comment by jamieshark** [comment]
Another thought is to add a HOC media query wrapper that can handle MQ related things on the JS end. Particularly for the mobile menu, it allows us a bit more flexibility to conditionally render components rather than have to mess around with a lot of positioning with mobile layouts.

## Estimate (10-11)
- Simple media query style mixin that lets us differentiate between desktop and tablet contexts. (I believe this is already implemented)
- Mobile UI for the menu system. (4)
- Mobile form UI for the add new node form (2-3)
- Mobile adaptations to typography, node, and image asset (e.g. button) sizing (4)

**Comment by wwqrd** [comment]
# Estimate  (25)

- Simple media query style mixin that lets us differentiate between desktop and tablet contexts. (1)
- Mobile UI for the menu system. (8)
- Mobile form UI for the add new node form (8)
- Mobile adaptations to typography, node, and image asset (e.g. button) sizing (8)

**Comment by wwqrd** [comment]
@jamieshark Curious about this HOC idea, do you mean like?:

```javascript
const component = (props) =>
  <div>
    <mobile>...mobile specific components</mobile>
    <desktop>...desktop specific components</desktop>
  </div>
```

**Comment by rebeccamadsen** [comment]
Estimate (21)
--

- Simple media query style mixin that lets us differentiate between desktop and tablet contexts. (1)
- Mobile UI for the menu system. (8)
- Mobile form UI for the add new node form (8)
- Mobile adaptations to typography, node, and image asset (e.g. button) sizing (4)

**Comment by jthrilly** [comment]
## Estimate: 19+

- Simple media query style mixin that lets us differentiate between desktop and tablet contexts. (2)
- Mobile UI for the menu system. (1)
- Mobile form UI for the add new node form (8+)
- Mobile adaptations to typography, node, and image asset (e.g. button) sizing (8)

**Comment by jthrilly** [comment]
Clarification on "mobile UI for the menu system": this is simply adjusting the menu width and the zoom out effect, using the media query. The implementation details are already in the style guide. Definitely not an 8 hour task.

**Comment by jthrilly** [comment]
I'm removing the "Mobile UI for add new node form" subtask as I think its marginally too big for a single subtask. It has multiple new components and a lot of CSS.  I will put it at the back of the queue for this release, so we will get to it if we can - if not, it will be in beta 2.

**Comment by jthrilly** [comment]
> Another thought is to add a HOC media query wrapper that can handle MQ related things on the JS end. Particularly for the mobile menu, it allows us a bit more flexibility to conditionally render components rather than have to mess around with a lot of positioning with mobile layouts.

Great suggestion! For the menu, where we have the same component, just with slightly different CSS (seriously - like three properties), I think we should do this the conventional way. However, this would be a perfect approach for the mobile add new node form, which has a very different flow and might actually be a different "wrapper" component. Will reference this idea in the new issue.
