### ISSUE TITLE
Implement dialog component (8)

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#194]
# Overview
We need to implement a dialog component for the app.

- Info, Error, Warning types, with associated icon and color.
- Buttons: in the abstract, we need to support a truthy button and a falsey button, and have only the truthy button be required for any dialog type.

Below is a form validation error to use as design inspiration: 
<img width="939" alt="screen shot 2017-08-07 at 3 58 21 pm" src="https://user-images.githubusercontent.com/1387940/29032448-4c394c5e-7b89-11e7-87c6-b68a016c2e92.png">

# Tasks:

- [x] Create dialogue reducer (1)
- [x] Add Error, Info, Warning actions to reducer (1)
- [x] Create dialogue component (1)
- [x] Style dialogue component (4)
- [x] Add dialogue to App container? (1)

**Comment by wwqrd** [comment]
## Estimate (7)

- Create dialogue reducer (0.5)
- Add Error, Info, Warning actions to reducer (1)
- Create dialogue component (0.5)
- Style dialogue component (4)
- Add dialogue to App container? (1)

**Comment by jthrilly** [comment]
## Estimate: 8

- Create dialogue reducer (1)
- Add Error, Info, Warning actions to reducer (1)
- Create dialogue component (1)
- Style dialogue component (4)
- Add dialogue to App container? (1)

**Comment by rebeccamadsen** [comment]
Estimate (8)
--

- Create dialogue reducer (1)
- Add Error, Info, Warning actions to reducer (1)
- Create dialogue component (1)
- Style dialogue component (4)
- Add dialogue to App container (1)
